services:
  mongo:
    image: mongo:6
    container_name: mongo_c
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_c
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb+srv://birhanabate17_db_user:gz6Ce6vk3Jhohcxi@cluster0.54vurld.mongodb.net/musicapp
    depends_on:
      - mongo
    volumes:
      - ./backend:/server
      - server_node_modules:/server/node_modules

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend_c
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/frontendapp
  #     - frontend_node_modules:/frontendapp/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

volumes:
  server_node_modules:
  # frontend_node_modules:
  mongo_data: